name: build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: unzip max-mod.zip
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current
      - run: gradle build
        working-directory: max-mod
      - uses: actions/upload-artifact@v4
        with:
          name: max-mod-jar
          path: max-mod/build/libs/*.jar
